name: Sync Submodule

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Update submodule
        run: |
          git submodule update --remote --recursive
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Update libuiohook submodule'
          body: 'This PR updates the libuiohook submodule to the latest version.'
          branch: update-libuiohook-submodule
          labels: submodule-update